Добавлена стилизация
htmlacademy-htmlcss/2081937-sedona-34 pull request #4
Opened 2022-06-14 21:28 UTC by renbiw

2022-06-15 09:59 UTC, nikopol-fw requested changes

2022-06-15 09:59 UTC, nikopol-fw commented on styles/styles.css
>      height:37px;
Не надо задавать строгие размеры элементам. ты лишаешь их гибкости. Нужные размеры достигаются за счёт внутренних отступов padding

2022-06-15 09:59 UTC, nikopol-fw commented on styles/styles.css
>      line-height: 21px;
Стили по умолчанию для текста выбраны не лучшим образом. По умолчанию стоит ориентироваться на обычный текст, в больших текстовых блоках, а не на заголовки. Сама подумай, по умолчанию весь добавленный текст будет жирным.

У тебя так получается, что макет небольшой, всего 2-е страницы, а теоретически видно что у сайта их больше. И на всех страницах нет больших объемов текста и заголовки встречаются чаще всего. Но хорошим примером общего текста всё же являются: на главной описание черным текстом `#333333` у преимуществ, в каталоге тип и цена у гостиниц, подпись у селектора "Гостиниц на странице", — стили одинаковые у этих текстов, погрешность в высоте строки можно игнорировать и задать свою (вообще странно видеть высоту строки, например в 23,29px)

Таким образом после правки базового стиля текста, проверить, чтобы цвета, размеры и начертание для текстов были корректны

2022-06-15 09:59 UTC, nikopol-fw commented on styles/styles.css
> +    height:60px;
Также следует удалить строгие размеры для элемента

2022-06-15 09:59 UTC, nikopol-fw commented on styles/styles.css
> +.submite-button{
Не самое удачное название для класса? А если будут другие submit кнопки?
Всё-таки лучше завести какой-то название для блока, например subscription, и называть классы элементов через него.

2022-06-15 09:59 UTC, nikopol-fw commented on styles/styles.css
>  }
У кнопки некорректное начертание font-weight

2022-06-15 09:59 UTC, nikopol-fw commented on styles/styles.css
> +}
Лучше задать наследование всех свойств текста, а не только font-family. Можно написать через общее правило `font: inherit`

2022-06-15 09:59 UTC, nikopol-fw commented on styles/styles.css
> +}
У кнопок submit и reset оформление текста разница с макетом

2022-06-15 09:59 UTC, nikopol-fw commented on styles/styles.css
> +}
Всё оформление лучше перенести в ссылку, потому что потом интерактивные стили будут применяться к ссылке, и размеры квадрата скругленного должны соответствовать ссылке, а не только цифра внутри. Иначе будет неудобно пользоваться

2022-06-17 21:43 UTC, renbiw commented on styles/styles.css
> +}
Перенесла оформление на ссылки, но размер уменьшается до размера цифр паджинации, указала внутренние отступы, но, думаю, это по другому делается

2022-06-18 11:06 UTC, nikopol-fw approved these changes

2022-06-18 11:06 UTC, merged