Сетки
htmlacademy-htmlcss/2081937-sedona-34 pull request #5
Opened 2022-06-25 14:12 UTC by renbiw

2022-06-26 11:42 UTC, nikopol-fw requested changes

2022-06-26 11:42 UTC, nikopol-fw commented on styles/styles.css
> +    height: 384px;
Убрать высоту

2022-06-26 11:42 UTC, nikopol-fw commented on styles/styles.css
> +    height: 384px;
Убрать высоту

2022-06-26 11:42 UTC, nikopol-fw commented on styles/styles.css
> +    margin-top: 92px;
margin-top следует заменить на padding у родителя

2022-06-26 11:42 UTC, nikopol-fw commented on styles/styles.css
> +    max-width: 190px;
Маленькое значение выделено под ширину списка соц. сетей

2022-06-26 11:42 UTC, nikopol-fw commented on styles/styles.css
> +.button-close {
Кнопку из span нужно переделать в button type="button"

2022-06-26 11:42 UTC, nikopol-fw commented on styles/styles.css
> +    width: 100%;
Св-во width: 100% не имеет смысла и ничего не меняет в этом месте

2022-06-26 11:42 UTC, nikopol-fw commented on styles/styles.css
> +}
А если отелей будет 7, 10, 13 и т.д.? Пока просто удалить эти правила с margin-left

2022-06-26 11:42 UTC, nikopol-fw commented on styles/styles.css
>  .rating span {
Уйти от тега, и всё-таки дать свой собственный класс

2022-06-26 11:42 UTC, nikopol-fw commented on styles/styles.css
> +    width: 400px;
Ширину пока просто урать

2022-06-26 11:42 UTC, nikopol-fw commented on styles/styles.css
> +.select-amount {
Соседний span `info-abt-amount-host` переделать на label

2022-06-26 12:23 UTC, renbiw commented on styles/styles.css
> +    max-width: 190px;
Указала ширину больше, но в контейнере "footer-social" указала распределение space-between, все равно отступ между элементами большой и на указанную ширину не растягивается список соц. сетей

2022-06-26 12:24 UTC, renbiw commented on styles/styles.css
> +.select-amount {
Переделала на label, надо ли связывать элемент info-abt-amount-host и select-amount, в котором выводится инфо о количестве отелей на странице?

2022-06-30 23:11 UTC, nikopol-fw commented on styles/styles.css
>  }
Ошибка `line-height: 26p;`

2022-06-30 23:11 UTC, nikopol-fw commented on styles/styles.css
> +}
`height: 561px;` — следует удалить ограничение по высоте

2022-06-30 23:11 UTC, nikopol-fw approved these changes

2022-06-30 23:14 UTC, merged